# Generated by Django 2.2.5 on 2019-09-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(help_text='Enter firstname', max_length=20)),
                ('lastName', models.CharField(help_text='Enter lastname', max_length=20)),
                ('dateOfBirth', models.CharField(help_text='Enter date of birth', max_length=20)),
                ('email', models.CharField(help_text='Enter email', max_length=20)),
                ('userName', models.CharField(help_text='Enter username', max_length=20)),
                ('passWord', models.CharField(help_text='Enter password', max_length=20)),
                ('retypePassWord', models.CharField(help_text='Retype Password', max_length=20)),
            ],
        ),
    ]
