# Generated by Django 2.2.5 on 2019-10-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20191002_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(help_text='Name of provided recipe', max_length=20)),
                ('recipe_image', models.ImageField(default='static/recipes/default.png', upload_to='images/')),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
