# Generated by Django 2.2.5 on 2019-12-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20191020_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_slug',
            field=models.SlugField(default='slug'),
        ),
    ]
