# Generated by Django 2.2.5 on 2019-12-03 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_recipe_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_slug',
            new_name='recipe_url',
        ),
    ]
